import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'date/index': 'src/date/index.ts',
    'string/index': 'src/string/index.ts',
    'number/index': 'src/number/index.ts',
    'status/index': 'src/status/index.ts',
    'auth/index': 'src/authentication/index.ts',
    'search/index': 'src/search/index.ts',
    'hooks/index': 'src/hooks/index.ts',
    'hooks/use-counter': 'src/hooks/use-counter.ts',
    'i18n/index': 'src/i18n/index.ts',
    'i18n/pt-br': 'src/i18n/pt-br.ts',
  },
  format: ['cjs', 'esm'],
  tsconfig: './tsconfig.json',
  dts: {
    entry: {
      index: 'src/index.ts',
      'date/index': 'src/date/index.ts',
      'string/index': 'src/string/index.ts',
      'number/index': 'src/number/index.ts',
      'status/index': 'src/status/index.ts',
      'auth/index': 'src/authentication/index.ts',
      'search/index': 'src/search/index.ts',
      'hooks/index': 'src/hooks/index.ts',
      'hooks/use-counter': 'src/hooks/use-counter.ts',
      'i18n/index': 'src/i18n/index.ts',
      'i18n/pt-br': 'src/i18n/pt-br.ts',
    },
  },
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  minify: false,
  target: 'es2020',
});
