import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'date/index': 'src/date/index.ts',
    'string/index': 'src/string/index.ts',
    'number/index': 'src/number/index.ts',
    'status/index': 'src/status/index.ts',
    'auth/index': 'src/authentication/index.ts',
    'search/index': 'src/search/index.ts',
    'hooks/index': 'src/hooks/index.ts',
    'hooks/use-counter': 'src/hooks/use-counter.ts',
    'i18n/index': 'src/i18n/index.ts',
    'i18n/pt-br': 'src/i18n/pt-br.ts',
    // Missing entries that are imported in index.ts
    'types': 'src/types.ts',
    'error': 'src/error/index.ts',
    'color': 'src/color/index.ts',
    'validation': 'src/validation/index.ts',
    'dom': 'src/dom/index.ts',
    'stats': 'src/stats/index.ts',
    'image': 'src/image/index.ts',
    'cookie': 'src/cookie/index.ts',
    'crypto': 'src/crypto/index.ts',
    'storage': 'src/storage/index.ts',
    'formatting': 'src/formatting/index.ts',
  },
  format: ['cjs', 'esm'],
  tsconfig: './tsconfig.json',
  dts: false,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  minify: false,
  target: 'es2020',
});
